# Generated by Django 5.2.1 on 2025-05-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="snils",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Снилс"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="Фамилия"
            ),
        ),
    ]
