# Generated by Django 5.2.1 on 2025-05-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_snils_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Ваш номер телефона"),
                ),
                ("question", models.TextField(verbose_name="Ваш вопрос")),
                (
                    "contact_time",
                    models.CharField(
                        max_length=50, verbose_name="Когда с вами связаться?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
