# Generated by Django 5.2.1 on 2025-05-10 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Имя"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Фамилия"
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Специальность",
                    ),
                ),
                (
                    "experience",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Стаж работы",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Адрес клиники",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Отзыв"
                    ),
                ),
                (
                    "rate",
                    models.CharField(
                        choices=[
                            ("5", "Все отлично!"),
                            ("4", "Все хорошо."),
                            ("3", "Есть замечания"),
                            ("2", "Не устроило"),
                            ("1", "Категорически не устроило"),
                        ],
                        max_length=10,
                        verbose_name="Количество звезд",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "addres",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Клиника на Малыгина", "Ул.Малыгина 44, 1 этаж"),
                            ("Клиника на Федюнинского", "Ул.Федюнинского 3, 1 этаж"),
                        ],
                        max_length=255,
                        null=True,
                        verbose_name="Адрес клиники",
                    ),
                ),
                ("patient_name", models.CharField(max_length=100)),
                ("appointment_date", models.DateTimeField()),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mvita_main.doctors",
                    ),
                ),
                (
                    "services",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mvita_main.services",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiagnosticResults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "results",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Результаты диагностики",
                    ),
                ),
                (
                    "record",
                    models.ForeignKey(
                        blank=True,
                        max_length=255,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mvita_main.record",
                        verbose_name="Запись",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="doctors",
            name="reviews",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mvita_main.reviews",
                verbose_name="Отзывы на врача",
            ),
        ),
    ]
