# Generated by Django 5.2.1 on 2025-05-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvita_main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="information",
            name="information",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Главная информация"
            ),
        ),
    ]
