# Generated by Django 5.2.1 on 2025-05-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvita_main", "0002_information_information"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="description",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Описание услуги"
            ),
        ),
        migrations.AddField(
            model_name="services",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Название услуги"
            ),
        ),
    ]
