# Generated by Django 5.2.1 on 2025-05-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvita_main", "0003_services_description_services_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="information",
            name="information",
            field=models.TextField(
                blank=True, max_length=255, null=True, verbose_name="Главная информация"
            ),
        ),
    ]
