# Generated by Django 5.2.1 on 2025-05-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvita_main", "0004_alter_information_information"),
    ]

    operations = [
        migrations.AlterField(
            model_name="information",
            name="information",
            field=models.TextField(
                blank=True, null=True, verbose_name="Главная информация"
            ),
        ),
    ]
