# Generated by Django 5.2.1 on 2025-05-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvita_main", "0005_alter_information_information"),
    ]

    operations = [
        migrations.AddField(
            model_name="services",
            name="price",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Цена"
            ),
        ),
    ]
