# Generated by Django 5.2.1 on 2025-05-18 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvita_main", "0006_services_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="appointment_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="patient_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="services",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mvita_main.services",
            ),
        ),
    ]
