# Generated by Django 5.2.1 on 2025-05-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvita_main", "0007_alter_record_appointment_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="addres",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Адрес клиники"
            ),
        ),
    ]
