# Generated by Django 5.2.1 on 2025-05-18 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvita_main", "0008_alter_record_addres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mvita_main.doctors",
            ),
        ),
    ]
