# Generated by Django 5.2.1 on 2025-05-19 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mvita_main", "0009_alter_record_doctor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="record",
            old_name="addres",
            new_name="address",
        ),
    ]
