# Generated by Django 5.2.1 on 2025-05-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvita_main", "0010_rename_addres_record_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="information",
            old_name="address",
            new_name="info2",
        ),
        migrations.RenameField(
            model_name="information",
            old_name="phone",
            new_name="info3",
        ),
        migrations.RemoveField(
            model_name="information",
            name="information",
        ),
        migrations.AddField(
            model_name="information",
            name="info1",
            field=models.CharField(
                blank=True, max_length=1020, null=True, verbose_name="О нашей компании"
            ),
        ),
        migrations.AddField(
            model_name="information",
            name="info4",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="information",
            name="info5",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Наш путь"
            ),
        ),
        migrations.AddField(
            model_name="information",
            name="info6",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Наша миссия"
            ),
        ),
        migrations.AddField(
            model_name="information",
            name="info7",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Наши ценности"
            ),
        ),
        migrations.AddField(
            model_name="information",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Цена"
            ),
        ),
    ]
