# Generated by Django 5.2.1 on 2025-05-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvita_main", "0011_rename_address_information_info2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="information",
            name="info2",
            field=models.CharField(
                blank=True, max_length=1020, null=True, verbose_name="Адрес клиники"
            ),
        ),
        migrations.AlterField(
            model_name="information",
            name="info3",
            field=models.CharField(
                blank=True, max_length=1020, null=True, verbose_name="Номер телефона"
            ),
        ),
        migrations.AlterField(
            model_name="information",
            name="info4",
            field=models.CharField(
                blank=True, max_length=1020, null=True, verbose_name="Email"
            ),
        ),
        migrations.AlterField(
            model_name="information",
            name="info5",
            field=models.CharField(
                blank=True, max_length=1020, null=True, verbose_name="Наш путь"
            ),
        ),
        migrations.AlterField(
            model_name="information",
            name="info6",
            field=models.CharField(
                blank=True, max_length=1020, null=True, verbose_name="Наша миссия"
            ),
        ),
        migrations.AlterField(
            model_name="information",
            name="info7",
            field=models.CharField(
                blank=True, max_length=1020, null=True, verbose_name="Наши ценности"
            ),
        ),
    ]
