# Generated by Django 5.2.1 on 2025-05-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvita_main", "0013_diagnosticresults_user_record_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="information",
            name="image_main",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
