# Generated by Django 5.2.1 on 2025-05-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvita_main", "0014_information_image_main"),
    ]

    operations = [
        migrations.AlterField(
            model_name="information",
            name="image_main",
            field=models.ImageField(
                blank=True, max_length=555, null=True, upload_to=""
            ),
        ),
    ]
