# Generated by Django 5.2.1 on 2025-05-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvita_main", "0015_alter_information_image_main"),
    ]

    operations = [
        migrations.AlterField(
            model_name="information",
            name="image_main",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="mvita_main/",
                verbose_name="Фото с главной страницы",
            ),
        ),
    ]
