# Generated by Django 5.2.1 on 2025-05-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mvita_main", "0017_alter_information_image_main"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctors",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=555,
                null=True,
                upload_to="mvita_main/",
                verbose_name="Фото врача",
            ),
        ),
        migrations.AlterField(
            model_name="information",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Название"
            ),
        ),
    ]
